version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

volumes:
  influxdbv2:

