version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=maxlogorg
      - DOCKER_INFLUXDB_INIT_BUCKET=maxlogbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=maxlogadmintoken

volumes:
  influxdbv2:


